### PR TITLE
Generate Python object docs from docstrings and add version number on homepage

### PR DESCRIPTION
**Pull request by mtazzari**
The docs/py_API.rst file shows how to refer to Python objects/functions with urls and how to generate their documentation from the docstring.
@jeffjennings @rbooth200 pls have a look at the file, so you can write the docs you want.

### CODE REVIEW

**Comment by mtazzari** [comment]
Please merge if you're happy with it.

**Comment by rbooth200** [comment]
Does this work locally for you? I'm having problems making the docs on the IoA machines, which are not finding the "'sphinxcontrib.fulltoc" dependency.

**Comment by mtazzari** [comment]
It works locally for me.
You need to have sphinxcontrib-fulltoc installed. I've added it to
requirements.txt, just re-install frankenstein:

cd frankenstein (the outermost dir of the repo)
pip install -e .   # <-- this should install sphinxcontrib-fulltoc
make -c docs html # should produce docs with no errors

**Comment by rbooth200** [comment]
I'm still getting a problem, now with "contents.rst" missing

**Comment by mtazzari** [comment]
1) try removing the _build directory and make html again
2) paste me the whole sphinx output

**Comment by rbooth200** [comment]
Sorry, I thought I pasted the output earlier:

rab200@calx016 docs> rm -rf _build
rab200@calx016 docs> make html
Running Sphinx v1.6.6
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] py_API                                                

Sphinx error:
master file /data/rab200/WorkingCopies/frankenstein/docs/contents.rst not found
make: *** [html] Error 1

**Comment by mtazzari** [comment]
Weird, I cannot reproduce the error.
It might be that you have an old version of Sphinx (1.6.6), while I am
using v2.3.1.

I've found this https://github.com/readthedocs/readthedocs.org/issues/2569
I've attempted a solution, try with the latest commit I've just pushed.

**Comment by mtazzari** [comment]
Ok great! I merge this

**Pull request merged**
