### PR TITLE
Changing geometry to object-orientated interface [do not merge]

### PR DESCRIPTION
**Pull request by rbooth200**
Here is a suggested implementation of the new interface for the geometry fit. Let me know what you think. The interface is now more consistent with the fitters interface. To see how it all works, look at the new tests. 

It still needs docs and cleaning up - e.g. I will remove / hide the fit_geometry_gaussian function.

### CODE REVIEW

**Comment by mtazzari** [comment]
This is fine for me to rebase and merge, but you still have [do not merge] in the title: are you waiting to do something else in this PR?

**Comment by rbooth200** [comment]
If you're happy great. I need to check the docs etc, will do that now. I'll merge straight after unless you want to see it again

**Comment by mtazzari** [comment]
Oh right, the documentation.
For the time being, it's important that you just write complete docstrings
of classes and functions, will care about how to use the geometry objects
in tutorial/examples/cookbook later.
Please go ahead and merge when ready.

**Comment by rbooth200** [comment]
I've done the doc-strings - that's all I had in mind anyway.

**Pull request merged**
